### ISSUE TITLE
Hint List

### ISSUE THREAD

**Issue by khalefa-ow** [peter-ai/LLMSteer#1]
Can you please include the meaning of the values in the hint list?
In Bao, I see only a few numbers of hints [(link to Bao Code)](https://github.com/learnedsystems/BaoForPostgreSQL/blob/1c15600a6d0a5bf09b08405702889eb1783579ca/pg_extension/bao_planner.h#L434)

**Comment by peter-ai** [comment]
You can find the complete list of hints in the Bao appendix found here: https://rmarcus.info/appendix.html. I will add this to the readme for clarity as well.

**Comment by khalefa-ow** [comment]
Thank you
